development:
  adapter: postgresql
  database: public_stand_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: public_stand_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: public_stand_production
  pool: 5
  timeout: 5000
  username: johnnybowman
  password: 

